### PR TITLE
Add regex for <device selector>

### LINKED ISSUE #31: API path with <device selector>
https://github.com/AMWA-TV/nmos-audio-channel-mapping/blob/v1.0.x/docs/2.0.%20APIs.md#api-paths, unusually for NMOS specs, permits the API path to include an optional component to allow the same host/port to host multiple instances of the API. Besides being inconsistent with other NMOS APIs, there doesn't seem to be a spec/pattern for the `<device selector>` component?

### PR DESCRIPTION
**Pull request by garethsb**
Resolves #31.

### CODE REVIEW

**Comment by garethsb** [comment]
Would it be worth repeating or expanding upon this in the [Interoperability - NMOS IS-04 - Discovery](https://github.com/AMWA-TV/nmos-audio-channel-mapping/blob/v1.0.x/docs/3.1.%20Interoperability%20-%20NMOS%20IS-04.md#discovery) section? E.g. to add the note that there are other ways to provide human-readable information, such as the IS-04 Device `label` and `description`.

**Review by andrewbonney — APPROVED** [review]
Looks good.

On your comment, I'd be happy to see that, potentially adjusting the sentence to indicate a preference for UUIDs here, with the 'slot2B' type label reserved for IS-04.

**Comment by garethsb** [comment]
Thanks, Andrew.

> On your comment, I'd be happy to see that, potentially adjusting the sentence to indicate a preference for UUIDs here, with the 'slot2B' type label reserved for IS-04.

What do you mean by reserved for IS-04?

**Comment by andrewbonney** [comment]
I mean that if we encourage use of UUIDs in URL paths for IS-08, which match the Device ID, then it would only be necessary to include the string 'slot2B' in the Device label or description on the IS-04 side. as you suggested previously.

**Comment by garethsb** [comment]
Ahh!! I thought you meant device selectors like 'slot2B' should only be used by systems that implemented IS-04 as well, or only used by the spec or something! :-)

**Comment by garethsb** [comment]
Done.

**Review by peterbrightwell — APPROVED** [review]
LGTM

**Comment by garethsb** [comment]
One more point - I propose to replace the term **device selector** with **API selector**, which matches what we did in IS-10 (influenced by IS-08), especially if there isn't in fact a one-to-one mapping between an IS-04 Device and the IS-08 API.

**Comment by peterbrightwell** [comment]
We've discussed Gareth's point and will use api_selector, with an example for selecting on Device.

**Comment by garethsb** [comment]
Ready for review, @chris-gil, @peterbrightwell.

**Review by chris-gil — APPROVED** [review]
Approved following discussions

**Pull request merged**
